### ISSUE TITLE
Respecto del README

### ISSUE THREAD

**Issue by delucas** [Crakens/jrpg#2]
Es necesario que lo completen con el enlace a sus nombres de usuario en GitHub, **respetando el formato de dejar un espacio entre palabra y paréntesis**. :)
Además, vayan pensando el nombre para el juego y agreguen un fragmento en el cual redactarán la pequeña historia que lo ambienta.

**Comment by delucas** [comment]
Sigue faltando el readme completo. La historia no está presente. Los menciono por si no recibieron notificaciones al respecto.

@pabloneto @ernestoalbrz @AnaLeonFuentes @daignespola @CosasDeJavi

**Comment by daignespola** [comment]
Corregido
