### ISSUE TITLE
Historias de Usuario y Criterios de Aceptación

### ISSUE THREAD

**Issue by delucas** [Crakens/jrpg#3]
Revisar y corregir las HA y los CA, conforme a los comentarios realizados en [este commit](https://github.com/Crakens/jrpg/commit/8cb39160d23e655a69f19c54b98376867000d13d#diff-bde4edde7f62b6285367c3f05cf1fb56).
Recuerden que son indicaciones generales, no son los único asuntos a atender. Al releer, redacten nuevamente todos los elementos tal que queden conforme lo indicado.

Tip -> https://github.com/programacion-avanzada/notas/wiki/Historias-de-Usuario-y-Criterios-de-Aceptaci%C3%B3n

**Comment by daignespola** [comment]
Corregidas las HU y los CA correspondientes.
